export function Footer() {
  return (
    <div className="site-footer">
      <div className="site-footer-inner">
        <div className="footer-links">
          <a href="/about" className="footer-link-item" style={{ textDecoration: 'none' }}>About</a>
          <a href="/data-sources" className="footer-link-item" style={{ textDecoration: 'none' }}>Data sources</a>
          <a href="/ai-transparency" className="footer-link-item" style={{ textDecoration: 'none' }}>AI transparency</a>
          <a href="/contact" className="footer-link-item" style={{ textDecoration: 'none' }}>Contact</a>
        </div>
        <div className="footer-copy">
          View the Board · Not affiliated with Loudoun County Government · Summaries generated by Gemma 4 from official public documents
        </div>
      </div>
    </div>
  )
}
