import { Navbar } from '@/components/Navbar'
import { Sidebar } from '@/components/Sidebar'
import { Footer } from '@/components/Footer'
import { ScrollReveal } from '@/components/ScrollReveal'

export const revalidate = 3600

const PROMPT_1 = `You are a plain-English rewriter for government meeting documents.
Analyze the official government meeting text below and return ONLY a valid JSON object.

Required JSON structure:
{
  "title": "<topic in plain English, maximum 10 words>",
  "summary": "<2-4 sentences for a general adult audience, no jargon>",
  "decisions": ["<exact decision or vote in plain language>"],
  "action_items": ["<next step or follow-up action>"],
  "key_figures": {
    "amounts": ["<dollar amounts mentioned>"],
    "vote_tallies": ["<vote results like '5-2 approved'>"],
    "dates": ["<specific dates mentioned>"],
    "schools": ["<specific school names mentioned>"]
  }
}`

const PROMPT_2 = `You are a classifier for local government meeting content.
The primary_category MUST be exactly one of these 12 slugs:
schools-education | school-construction | budget-finance | transportation |
zoning-land-use | public-safety | policy-governance | equity-inclusion |
technology | community-parks | personnel | general

Required JSON structure:
{
  "primary_category": "<one slug from the list above>",
  "secondary_tags": ["<specific sub-topic tag>"],
  "urgency": "<routine OR notable OR significant>",
  "fiscal_impact": true or false,
  "affects_schools": ["<school name if mentioned>"]
}`

const PROMPT_3 = `You are a civic reporter summarising a complete government board meeting.
From the agenda item summaries below, produce a meeting overview.

Required JSON structure:
{
  "overview": "<3-5 sentence narrative of the full meeting>",
  "top_decisions": ["<top 3 most significant decisions>"],
  "fiscal_total": "<total dollar amount of fiscal decisions, or null>"
}`

export default function AITransparencyPage() {
  return (
    <div className="site">
      <Navbar />
      <ScrollReveal />

      <div className="page-layout">
        <Sidebar />

        <div className="site-container">
          <div className="info-page">

            <div className="info-section" data-reveal>
              <div className="info-eyebrow">AI Transparency</div>
              <h1 className="info-title">How Gemma 4 powers View the Board</h1>
              <div className="info-body">
                <p>
                  Every summary on this site is generated by <strong>Gemma 4</strong> — Google DeepMind's open
                  model — running locally via Ollama. No data is sent to any external AI service. This page
                  explains exactly what the model does and how we validate its output.
                </p>
              </div>
            </div>

            <div className="info-section" data-reveal>
              <div className="info-eyebrow">Prompt 1 of 3</div>
              <h2 className="info-title" style={{ fontSize: 18 }}>Plain-English rewrite</h2>
              <div className="info-body">
                <p>
                  Each agenda item chunk (max ~2,000 characters) is sent with this prompt. Gemma 4 returns a
                  structured JSON object — no free-form text. Ollama's <code>format</code> parameter enforces
                  the exact JSON schema.
                </p>
                <pre className="info-prompt-block">{PROMPT_1}</pre>
              </div>
            </div>

            <div className="info-section" data-reveal>
              <div className="info-eyebrow">Prompt 2 of 3</div>
              <h2 className="info-title" style={{ fontSize: 18 }}>Classification</h2>
              <div className="info-body">
                <p>
                  The rewritten summary (not the raw PDF text) is classified into one of 12 category slugs with
                  an urgency level and fiscal flag. Running classification on the plain-English version gives the
                  model better context about intent rather than bureaucratic phrasing.
                </p>
                <pre className="info-prompt-block">{PROMPT_2}</pre>
              </div>
            </div>

            <div className="info-section" data-reveal>
              <div className="info-eyebrow">Prompt 3 of 3</div>
              <h2 className="info-title" style={{ fontSize: 18 }}>Meeting overview</h2>
              <div className="info-body">
                <p>
                  After all items are processed, all summaries are concatenated and sent once to produce a
                  meeting-level narrative. This prompt runs once per meeting, not once per item, keeping
                  processing proportional to meetings rather than agenda items.
                </p>
                <pre className="info-prompt-block">{PROMPT_3}</pre>
              </div>
            </div>

            <div className="info-section" data-reveal>
              <div className="info-eyebrow">Validation & retry</div>
              <div className="info-body">
                <p>
                  All responses are validated against Pydantic models. If Gemma 4 returns malformed JSON or
                  missing fields, the prompt is retried up to 2 times with an explicit correction instruction.
                  The observed failure rate before retry is ~8%; after retry it drops to under 1%.
                </p>
                <p>
                  <strong>Every AI-generated summary is linked to its official source PDF</strong> so you can
                  verify any claim independently.
                </p>
              </div>
            </div>

            <div className="info-section" data-reveal>
              <div className="info-eyebrow">What the AI does not do</div>
              <div className="info-body">
                <p>
                  Gemma 4 only processes text that appears in official agenda documents. It does not browse the
                  internet, access live county systems, or use information from outside the source PDF. It cannot
                  form opinions and is not asked to.
                </p>
                <p>
                  Vote tallies, dollar figures, and school names are extracted verbatim from the document — the
                  model is instructed to copy these exactly, not paraphrase them.
                </p>
              </div>
            </div>

          </div>
        </div>
      </div>

      <Footer />
    </div>
  )
}
