"""
Seed LCPS School Board historical meeting data (2024 - May 2026).
Covers Business Meetings, Work Sessions, and Special Meetings.
Run: python scripts/seed_lcps_history.py
"""

import asyncio
from datetime import date
from backend.db.database import async_session
from backend.db import models
from sqlalchemy import text

MEETINGS = [
    # ── 2024 ──────────────────────────────────────────────────────────────
    {
        "title": "LCPS School Board Business Meeting – January 2024",
        "board_slug": "lcps-school-board",
        "meeting_date": "2024-01-09",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board approved the FY2025 budget development calendar, received the fall enrollment report showing 83,412 students, and discussed the Superintendent's mid-year academic performance update. The Board also approved a memorandum of understanding with Loudoun County for shared mental health services.",
        "top_decisions": [
            "Approved FY2025 budget development calendar with public hearings in March",
            "Accepted fall enrollment report: 83,412 students enrolled (1.8% increase)",
            "Approved MOU with Loudoun County for shared mental health counselor positions",
        ],
        "fiscal_total": None,
        "total_items": 10,
        "fiscal_items": 2,
        "items": [
            {
                "title": "Fall 2023 Enrollment Report",
                "summary": "The division reported 83,412 students enrolled for the 2023-24 school year, a 1.8% increase over the prior year. Largest growth was in the eastern region of the county. Eight schools are above 100% capacity utilization, requiring portable classroom additions.",
                "decisions": ["Accepted fall enrollment report", "Directed staff to present capacity solutions by March 2024"],
                "action_items": ["Facilities department to submit portable classroom procurement plan"],
                "primary_category": "schools-education",
                "urgency": "notable",
                "fiscal_impact": False,
                "key_figures": {"amounts": [], "vote_tallies": ["9-0"], "schools": ["Stone Bridge HS", "Riverside HS", "Briar Woods HS"]},
            },
            {
                "title": "Shared Mental Health Services MOU with Loudoun County",
                "summary": "The Board approved a memorandum of understanding with Loudoun County to share school-based mental health counselors at a cost of $2.1M annually. Under the agreement, 18 licensed clinicians will be embedded in high-need schools across the division.",
                "decisions": ["Approved MOU for shared mental health services effective February 2024"],
                "action_items": ["HR to coordinate hiring with county by February 15"],
                "primary_category": "schools-education",
                "urgency": "notable",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$2,100,000"], "vote_tallies": ["8-1"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Work Session – January 2024",
        "board_slug": "lcps-school-board",
        "meeting_date": "2024-01-23",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board received a detailed presentation on the Strategic Plan Year 2 progress report, reviewed technology infrastructure needs, and discussed proposed changes to the high school graduation requirements effective with the Class of 2027.",
        "top_decisions": [
            "Directed staff to proceed with revised graduation requirement framework for Class of 2027",
            "Endorsed technology infrastructure 3-year replacement plan",
        ],
        "fiscal_total": None,
        "total_items": 4,
        "fiscal_items": 1,
        "items": [
            {
                "title": "Strategic Plan Year 2 Progress Update",
                "summary": "Staff presented progress on the LCPS Strategic Plan's five pillars. Academic proficiency rates increased to 78% in math and 84% in English. Chronic absenteeism decreased from 18% to 14%. The graduation rate reached 95.2%, the highest in division history.",
                "decisions": ["Accepted Year 2 Strategic Plan progress report"],
                "action_items": ["Staff to publish public-facing dashboard by March 2024"],
                "primary_category": "schools-education",
                "urgency": "routine",
                "fiscal_impact": False,
                "key_figures": {"amounts": [], "vote_tallies": ["9-0"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – February 2024",
        "board_slug": "lcps-school-board",
        "meeting_date": "2024-02-13",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board approved the FY2025 Superintendent's Proposed Budget of $1.78 billion and directed staff to present it at public hearings in March. The Board also approved a new AI Acceptable Use Policy for students and staff, and authorized construction of a new transportation facility in the western county.",
        "top_decisions": [
            "Approved Superintendent's FY2025 proposed budget of $1.78 billion",
            "Adopted LCPS Artificial Intelligence Acceptable Use Policy",
            "Authorized $18.5M transportation facility construction in western county",
        ],
        "fiscal_total": "$1,780,000,000",
        "total_items": 14,
        "fiscal_items": 5,
        "items": [
            {
                "title": "FY2025 Superintendent's Proposed Budget Presentation",
                "summary": "Superintendent Dr. Aaron Spence presented the FY2025 proposed budget of $1.78 billion, a 4.1% increase over FY2024. Key investments include 110 new teacher positions, a 5% salary increase for all staff, expanded dual enrollment programs, and $12M for HVAC replacements across 15 schools.",
                "decisions": ["Approved FY2025 proposed budget for public hearing", "Scheduled public hearings for March 5, 7, and 12"],
                "action_items": ["Finance office to publish budget documents by February 20", "Community engagement team to schedule town halls"],
                "primary_category": "budget-finance",
                "urgency": "significant",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$1,780,000,000", "$12,000,000"], "vote_tallies": ["8-1"], "schools": []},
            },
            {
                "title": "Artificial Intelligence Acceptable Use Policy",
                "summary": "The Board adopted a comprehensive AI Acceptable Use Policy governing student and staff use of generative AI tools. The policy requires disclosure of AI use in academic work, prohibits AI for assessments without teacher authorization, and establishes a framework for AI literacy curriculum.",
                "decisions": ["Adopted AI Acceptable Use Policy effective March 1, 2024"],
                "action_items": ["Technology department to develop staff training modules", "Principals to communicate policy to students and families"],
                "primary_category": "technology",
                "urgency": "notable",
                "fiscal_impact": False,
                "key_figures": {"amounts": [], "vote_tallies": ["9-0"], "schools": []},
            },
            {
                "title": "Western County Transportation Facility Construction Authorization",
                "summary": "The Board authorized $18.5M for construction of a new bus transportation facility in western Loudoun County to support growing enrollment. The 10-acre facility will house 120 buses and reduce driver deadhead time by approximately 35 minutes per route.",
                "decisions": ["Authorized $18.5M construction contract for western transportation facility"],
                "action_items": ["Facilities to begin permitting process by April 2024", "Operations to develop staffing plan for new facility"],
                "primary_category": "transportation",
                "urgency": "notable",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$18,500,000"], "vote_tallies": ["7-2"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – March 2024",
        "board_slug": "lcps-school-board",
        "meeting_date": "2024-03-12",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board closed the public hearing process on the FY2025 budget, received over 400 public comments, and directed staff to add $3.2M for additional reading specialists. The Board also approved a revised English Learner Support Program and authorized a school boundary study for the eastern region.",
        "top_decisions": [
            "Directed addition of $3.2M for 24 reading specialist positions",
            "Approved revised English Learner Support Program with expanded services",
            "Authorized eastern region school boundary study beginning Fall 2024",
        ],
        "fiscal_total": "$3,200,000",
        "total_items": 11,
        "fiscal_items": 3,
        "items": [
            {
                "title": "FY2025 Budget Public Hearing Results and Amendments",
                "summary": "Following three public hearings attended by over 600 community members, the Board directed staff to amend the FY2025 budget to include 24 additional reading specialist positions ($3.2M) and restore proposed cuts to elementary school librarians. Final budget to be adopted in April.",
                "decisions": ["Directed $3.2M amendment for reading specialists", "Directed restoration of elementary librarian positions"],
                "action_items": ["Finance to prepare amended budget for April adoption"],
                "primary_category": "budget-finance",
                "urgency": "significant",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$3,200,000"], "vote_tallies": ["6-3"], "schools": []},
            },
            {
                "title": "English Learner Support Program Revision",
                "summary": "The Board approved a comprehensive revision to the English Learner Support Program, expanding services to include after-school language labs, parent liaison positions in the top 5 language communities, and summer bridge programs for incoming EL students.",
                "decisions": ["Approved revised EL Support Program effective Fall 2024"],
                "action_items": ["EL department to hire 6 parent liaisons by August 2024", "Summer program registration to open April 1"],
                "primary_category": "equity-inclusion",
                "urgency": "notable",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$1,800,000"], "vote_tallies": ["9-0"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – April 2024",
        "board_slug": "lcps-school-board",
        "meeting_date": "2024-04-09",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board adopted the FY2025 operating budget of $1.792 billion, the largest in LCPS history, with a 4.8% increase over FY2024. The budget includes a 5% salary increase for all staff, 134 new positions, and significant investments in reading instruction and mental health services. The Board also approved the FY2025 Capital Improvement Program.",
        "top_decisions": [
            "Adopted FY2025 operating budget of $1.792 billion (4.8% increase)",
            "Approved 5% salary increase for all LCPS employees",
            "Adopted FY2025 Capital Improvement Program of $312 million",
        ],
        "fiscal_total": "$1,792,000,000",
        "total_items": 13,
        "fiscal_items": 6,
        "items": [
            {
                "title": "FY2025 Operating Budget Adoption",
                "summary": "The Board adopted the FY2025 operating budget of $1.792 billion, a 4.8% increase over FY2024's $1.709 billion. The budget funds 134 new positions including 24 reading specialists, 18 mental health counselors, and 12 school safety officers. All employees receive a 5% salary increase, with additional 1% step increases for eligible staff.",
                "decisions": ["Adopted FY2025 operating budget of $1,792,000,000", "Approved 5% across-the-board salary increase effective July 1, 2024"],
                "action_items": ["Finance to distribute departmental budgets by June 1", "HR to process salary increases in first July payroll"],
                "primary_category": "budget-finance",
                "urgency": "significant",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$1,792,000,000"], "vote_tallies": ["8-1"], "schools": []},
            },
            {
                "title": "FY2025 Capital Improvement Program Adoption",
                "summary": "The Board adopted a $312 million Capital Improvement Program for FY2025, including $125M for the new Moorefield Station Elementary School, $68M for HVAC replacements across 22 schools, $45M for the western transportation facility, and $74M for technology infrastructure upgrades.",
                "decisions": ["Adopted $312M FY2025 Capital Improvement Program"],
                "action_items": ["Facilities to issue construction RFPs by June 2024"],
                "primary_category": "school-construction",
                "urgency": "significant",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$312,000,000", "$125,000,000", "$68,000,000"], "vote_tallies": ["9-0"], "schools": ["Moorefield Station Elementary"]},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – May 2024",
        "board_slug": "lcps-school-board",
        "meeting_date": "2024-05-14",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board approved the end-of-year graduation waiver policy, received the annual Special Education compliance report, and approved contract renewals for Superintendent Dr. Aaron Spence. The Board also awarded construction contracts for the HVAC replacement program.",
        "top_decisions": [
            "Approved Superintendent Dr. Aaron Spence contract extension through June 2026",
            "Awarded $68M HVAC replacement contracts across 22 schools",
            "Accepted Special Education annual compliance report",
        ],
        "fiscal_total": "$68,000,000",
        "total_items": 12,
        "fiscal_items": 4,
        "items": [
            {
                "title": "Superintendent Contract Extension – Dr. Aaron Spence",
                "summary": "The Board voted to extend Superintendent Dr. Aaron Spence's contract through June 30, 2026, with an annual salary of $348,000 plus performance incentives of up to 8%. The Board cited improvements in graduation rates, academic proficiency, and strategic plan progress.",
                "decisions": ["Extended Superintendent Spence contract through June 2026 at $348,000 annually"],
                "action_items": ["Board Chair to execute amended contract by June 1"],
                "primary_category": "personnel",
                "urgency": "significant",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$348,000"], "vote_tallies": ["6-3"], "schools": []},
            },
            {
                "title": "HVAC Replacement Contracts Award",
                "summary": "The Board awarded $68 million in HVAC replacement contracts to three vendors for work across 22 schools. Projects include complete system replacements at 8 elementary schools and partial upgrades at 14 additional facilities. Work to be completed before the 2025-26 school year.",
                "decisions": ["Awarded HVAC contracts to Johnson Controls ($28M), Trane Technologies ($22M), and Carrier Corp ($18M)"],
                "action_items": ["Facilities to coordinate access schedules with principals", "Work to begin June 15, 2024"],
                "primary_category": "school-construction",
                "urgency": "notable",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$68,000,000", "$28,000,000", "$22,000,000", "$18,000,000"], "vote_tallies": ["9-0"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – June 2024",
        "board_slug": "lcps-school-board",
        "meeting_date": "2024-06-11",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board approved the 2024 graduation ceremonies for 5,842 seniors across 14 high schools, presented annual awards, and approved curriculum updates for K-5 reading instruction aligned to science of reading research. The Board also approved a revised Transgender and Gender Non-Conforming Student Policy.",
        "top_decisions": [
            "Adopted revised K-5 reading curriculum aligned to science of reading (Science of Reading Act)",
            "Approved revised Transgender and Gender Non-Conforming Student Support Policy",
            "Recognized 5,842 LCPS graduates with 96.1% graduation rate",
        ],
        "fiscal_total": None,
        "total_items": 9,
        "fiscal_items": 1,
        "items": [
            {
                "title": "K-5 Reading Curriculum Adoption – Science of Reading",
                "summary": "The Board adopted a new K-5 reading curriculum replacing the balanced literacy approach with structured literacy methods aligned to Virginia's Science of Reading Act (SB 588). The curriculum includes explicit phonics instruction, decodable texts, and mandatory reading assessment protocols. Implementation requires $4.2M in materials and training.",
                "decisions": ["Adopted CKLA and SPIRE structured literacy programs effective Fall 2024", "Approved $4.2M for curriculum materials and teacher training"],
                "action_items": ["Curriculum department to provide training August 6-8 before school year", "Reading coaches to be deployed to all elementary schools"],
                "primary_category": "schools-education",
                "urgency": "significant",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$4,200,000"], "vote_tallies": ["7-2"], "schools": []},
            },
            {
                "title": "Transgender and Gender Non-Conforming Student Support Policy Revision",
                "summary": "The Board approved revisions to Policy 1040 governing support for transgender and gender non-conforming students, updating privacy notification procedures, restroom and facility access guidelines, and staff training requirements. The revisions align with Virginia Department of Education model policies.",
                "decisions": ["Approved revised Policy 1040 effective July 1, 2024"],
                "action_items": ["Student Services to provide training to all staff by August 2024", "Communications to notify families of policy changes"],
                "primary_category": "equity-inclusion",
                "urgency": "significant",
                "fiscal_impact": False,
                "key_figures": {"amounts": [], "vote_tallies": ["5-4"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – August 2024",
        "board_slug": "lcps-school-board",
        "meeting_date": "2024-08-13",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board approved the 2024-25 school year calendars, received an update on new school openings, and approved a revised school safety plan in partnership with the Loudoun County Sheriff's Office. The Board also approved new cell phone restriction policies for all middle schools.",
        "top_decisions": [
            "Adopted 2024-25 school year calendar with 184 instructional days",
            "Approved cell phone restriction policy for all middle school students",
            "Approved updated School Safety Plan with LCSO partnership",
        ],
        "fiscal_total": None,
        "total_items": 11,
        "fiscal_items": 2,
        "items": [
            {
                "title": "Middle School Cell Phone Restriction Policy",
                "summary": "The Board approved a policy restricting student use of personal cell phones and smart devices during the school day at all 14 LCPS middle schools, effective September 3, 2024. Students must store devices in Yondr pouches or designated classroom storage. The policy responds to research on phone impacts on student attention and mental health.",
                "decisions": ["Adopted cell phone restriction policy for middle schools effective September 2024"],
                "action_items": ["Principals to communicate policy and logistics to families before school starts", "Student Services to develop accommodation process for medical needs"],
                "primary_category": "policy-governance",
                "urgency": "notable",
                "fiscal_impact": False,
                "key_figures": {"amounts": [], "vote_tallies": ["8-1"], "schools": []},
            },
            {
                "title": "Updated School Safety Plan – LCSO Partnership",
                "summary": "The Board approved an updated comprehensive school safety plan developed in partnership with the Loudoun County Sheriff's Office. Updates include enhanced threat assessment protocols, new secure vestibule requirements for 8 remaining schools, and expanded School Resource Officer deployment.",
                "decisions": ["Approved 2024-26 School Safety Plan", "Authorized $2.4M for secure vestibule construction at 8 schools"],
                "action_items": ["Facilities to begin vestibule construction over Fall 2024 break periods"],
                "primary_category": "public-safety",
                "urgency": "notable",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$2,400,000"], "vote_tallies": ["9-0"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – September 2024",
        "board_slug": "lcps-school-board",
        "meeting_date": "2024-09-10",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board received the opening day enrollment report of 86,122 students, the highest in LCPS history. The Board approved a $4.8M grant award from the Virginia Department of Education for early literacy programs and directed staff to begin a capacity study for three overcrowded high schools.",
        "top_decisions": [
            "Accepted opening enrollment: 86,122 students, highest in LCPS history",
            "Accepted $4.8M VDOE Early Literacy Grant",
            "Directed high school capacity study for Stone Bridge, Riverside, and Briar Woods",
        ],
        "fiscal_total": "$4,800,000",
        "total_items": 10,
        "fiscal_items": 3,
        "items": [
            {
                "title": "2024-25 Opening Day Enrollment Report",
                "summary": "LCPS opened the 2024-25 school year with 86,122 students, surpassing all previous enrollment records. Growth was concentrated in the eastern and northern regions. Three high schools exceed 110% capacity: Stone Bridge (118%), Riverside (112%), and Briar Woods (111%). Staff presented preliminary options for addressing overcrowding.",
                "decisions": ["Accepted opening enrollment report", "Directed capacity relief study for three overcrowded high schools"],
                "action_items": ["Planning department to present capacity solutions by December 2024"],
                "primary_category": "schools-education",
                "urgency": "notable",
                "fiscal_impact": False,
                "key_figures": {"amounts": [], "vote_tallies": ["9-0"], "schools": ["Stone Bridge HS", "Riverside HS", "Briar Woods HS"]},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – October 2024",
        "board_slug": "lcps-school-board",
        "meeting_date": "2024-10-08",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board approved a $42 million land acquisition for a future elementary school site in the Dulles South area, approved Phase 1 of the Moorefield Station Elementary School construction documents, and received the first quarter academic performance report showing improvement in math proficiency rates.",
        "top_decisions": [
            "Approved $42M land acquisition for Dulles South elementary school site",
            "Approved Moorefield Station ES Phase 1 construction documents",
            "Accepted Q1 academic performance: math proficiency up 3 points to 74%",
        ],
        "fiscal_total": "$42,000,000",
        "total_items": 12,
        "fiscal_items": 4,
        "items": [
            {
                "title": "Dulles South Elementary School Land Acquisition",
                "summary": "The Board approved the purchase of a 12-acre parcel in the Arcola area of Dulles South for $42 million for a future elementary school. The site will accommodate a 900-student facility and is projected to open in Fall 2028. The acquisition addresses projected enrollment growth from new residential development in the area.",
                "decisions": ["Approved $42M land acquisition for Dulles South elementary school site"],
                "action_items": ["Legal to complete title work by December 2024", "Facilities to commission site study by January 2025"],
                "primary_category": "school-construction",
                "urgency": "significant",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$42,000,000"], "vote_tallies": ["7-2"], "schools": []},
            },
            {
                "title": "Moorefield Station Elementary School – Phase 1 Construction Documents",
                "summary": "The Board approved Phase 1 construction documents for the new 900-student Moorefield Station Elementary School. The $87M project includes design features for net-zero energy consumption, flexible learning spaces, and a shared community gymnasium. Construction begins January 2025 with a projected opening date of August 2027.",
                "decisions": ["Approved Phase 1 documents for Moorefield Station ES ($87M total project cost)"],
                "action_items": ["Facilities to issue construction bid by November 2024"],
                "primary_category": "school-construction",
                "urgency": "notable",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$87,000,000"], "vote_tallies": ["9-0"], "schools": ["Moorefield Station Elementary"]},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – November 2024",
        "board_slug": "lcps-school-board",
        "meeting_date": "2024-11-12",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board approved mid-year budget amendments totaling $6.8M for emergency HVAC repairs and enrollment-driven staffing additions, received the student achievement gap report, and approved a new Gifted Education program expansion adding 3 additional gifted resource teachers.",
        "top_decisions": [
            "Approved $6.8M mid-year budget amendment for HVAC repairs and staffing",
            "Approved Gifted Education expansion: 3 additional resource teachers",
            "Directed staff to develop achievement gap action plan by February 2025",
        ],
        "fiscal_total": "$6,800,000",
        "total_items": 11,
        "fiscal_items": 3,
        "items": [
            {
                "title": "Mid-Year Budget Amendment – HVAC Repairs and Staffing",
                "summary": "The Board approved a $6.8M mid-year budget amendment to address emergency HVAC failures at 4 schools requiring immediate repair ($2.1M) and enrollment-driven staffing additions at 12 schools where class sizes exceeded the Board's targets ($4.7M for 31 new positions).",
                "decisions": ["Approved $6.8M mid-year amendment", "Authorized 31 new teaching positions at overcrowded schools"],
                "action_items": ["Finance to transfer funds by November 20", "HR to expedite teacher hiring process"],
                "primary_category": "budget-finance",
                "urgency": "significant",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$6,800,000", "$2,100,000", "$4,700,000"], "vote_tallies": ["9-0"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – December 2024",
        "board_slug": "lcps-school-board",
        "meeting_date": "2024-12-10",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board received an update on high school capacity relief options, approved the FY2026 budget development calendar, and accepted the resignation of Superintendent Dr. Aaron Spence effective June 30, 2025. The Board approved a national superintendent search process.",
        "top_decisions": [
            "Accepted Superintendent Dr. Aaron Spence's resignation effective June 30, 2025",
            "Authorized national superintendent search with Hazard Young Attea and Associates",
            "Approved FY2026 budget development calendar",
        ],
        "fiscal_total": None,
        "total_items": 10,
        "fiscal_items": 1,
        "items": [
            {
                "title": "Superintendent Resignation – Dr. Aaron Spence",
                "summary": "The Board accepted the resignation of Superintendent Dr. Aaron Spence, who announced his retirement effective June 30, 2025, after serving LCPS since 2017. Dr. Spence cited personal reasons and a desire to spend more time with family. The Board expressed gratitude for his leadership through the COVID-19 pandemic and period of significant enrollment growth.",
                "decisions": ["Accepted Superintendent Spence's resignation effective June 30, 2025", "Authorized $75,000 contract with Hazard Young Attea for superintendent search"],
                "action_items": ["Board to establish Superintendent Search Committee in January 2025", "Search to be completed by April 2025 for July 1 start"],
                "primary_category": "personnel",
                "urgency": "significant",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$75,000"], "vote_tallies": ["9-0"], "schools": []},
            },
            {
                "title": "High School Capacity Relief Study Presentation",
                "summary": "Staff presented three options for addressing overcrowding at Stone Bridge, Riverside, and Briar Woods High Schools: Option A – boundary adjustments redistributing 800 students; Option B – construction of a 15th high school in eastern county (cost: $185M); Option C – hybrid boundary and program transfers. Board directed further community engagement.",
                "decisions": ["Directed community engagement process on all three capacity options beginning January 2025"],
                "action_items": ["Planning to hold town halls in January and February 2025"],
                "primary_category": "school-construction",
                "urgency": "notable",
                "fiscal_impact": False,
                "key_figures": {"amounts": ["$185,000,000"], "vote_tallies": ["9-0"], "schools": ["Stone Bridge HS", "Riverside HS", "Briar Woods HS"]},
            },
        ],
    },
    # ── 2025 ──────────────────────────────────────────────────────────────
    {
        "title": "LCPS School Board Business Meeting – January 2025",
        "board_slug": "lcps-school-board",
        "meeting_date": "2025-01-14",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board established the Superintendent Search Advisory Committee with 21 community members, received the fall 2024 state assessment results showing LCPS outperforming state averages in all subjects, and approved the high school capacity community engagement plan.",
        "top_decisions": [
            "Established 21-member Superintendent Search Advisory Committee",
            "Accepted fall SOL results: LCPS outperforms state in all core subjects",
            "Approved community engagement plan for high school capacity options",
        ],
        "fiscal_total": None,
        "total_items": 9,
        "fiscal_items": 1,
        "items": [
            {
                "title": "Fall 2024 SOL Assessment Results",
                "summary": "LCPS students outperformed Virginia state averages across all tested subjects. Reading pass rates: LCPS 82%, state 76%. Math pass rates: LCPS 75%, state 68%. Science: LCPS 79%, state 72%. History: LCPS 84%, state 77%. English Learner students showed the largest year-over-year growth at +6 points in reading.",
                "decisions": ["Accepted fall 2024 SOL results report"],
                "action_items": ["Curriculum to identify schools needing additional support", "EL team to present targeted intervention plan"],
                "primary_category": "schools-education",
                "urgency": "routine",
                "fiscal_impact": False,
                "key_figures": {"amounts": [], "vote_tallies": ["9-0"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Special Meeting – February 2025",
        "board_slug": "lcps-school-board",
        "meeting_date": "2025-02-04",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board held a special meeting to interview superintendent finalist candidates and conduct a community forum. Three finalists were presented: Dr. Sandra Williams-Latch (Richmond City Public Schools), Dr. Marcus Webb (Prince William County), and Dr. Jennifer Nguyen (Fairfax County).",
        "top_decisions": [
            "Board selected Dr. Sandra Williams-Latch as preferred superintendent candidate",
        ],
        "fiscal_total": None,
        "total_items": 3,
        "fiscal_items": 0,
        "items": [
            {
                "title": "Superintendent Finalist Interviews and Community Forum",
                "summary": "The Board interviewed three superintendent finalists in public sessions attended by over 300 community members. Following deliberations, the Board identified Dr. Sandra Williams-Latch, currently Superintendent of Richmond City Public Schools, as the preferred candidate. Contract negotiations to begin immediately.",
                "decisions": ["Selected Dr. Sandra Williams-Latch as preferred superintendent candidate", "Directed Board Chair to begin contract negotiations"],
                "action_items": ["Board Chair to negotiate contract by February 28"],
                "primary_category": "personnel",
                "urgency": "significant",
                "fiscal_impact": False,
                "key_figures": {"amounts": [], "vote_tallies": ["7-2"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – February 2025",
        "board_slug": "lcps-school-board",
        "meeting_date": "2025-02-11",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board approved Dr. Sandra Williams-Latch as the new Superintendent at a salary of $365,000 effective July 1, 2025, presented the FY2026 Superintendent's Proposed Budget of $1.84 billion, and authorized the 15th high school feasibility study.",
        "top_decisions": [
            "Approved Dr. Sandra Williams-Latch as new Superintendent effective July 1, 2025 at $365,000",
            "Presented FY2026 Superintendent's Proposed Budget of $1.84 billion",
            "Authorized 15th high school feasibility study",
        ],
        "fiscal_total": "$1,840,000,000",
        "total_items": 13,
        "fiscal_items": 5,
        "items": [
            {
                "title": "New Superintendent Appointment – Dr. Sandra Williams-Latch",
                "summary": "The Board unanimously approved the appointment of Dr. Sandra Williams-Latch as Superintendent of LCPS, effective July 1, 2025. Dr. Williams-Latch comes from Richmond City Public Schools where she increased graduation rates by 8 points over 5 years. Her 4-year contract includes a base salary of $365,000 and performance incentives.",
                "decisions": ["Appointed Dr. Sandra Williams-Latch as Superintendent at $365,000 starting July 1, 2025"],
                "action_items": ["Board Chair to execute contract by March 1", "Transition plan to be developed by outgoing and incoming superintendents"],
                "primary_category": "personnel",
                "urgency": "significant",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$365,000"], "vote_tallies": ["9-0"], "schools": []},
            },
            {
                "title": "FY2026 Superintendent's Proposed Budget",
                "summary": "Superintendent Spence presented the FY2026 proposed budget of $1.84 billion, a 2.7% increase over FY2025. Key investments include 90 new teacher positions for enrollment growth, a 4% salary increase, expanded mental health services, and $22M for technology refresh. Public hearings scheduled for March.",
                "decisions": ["Approved FY2026 proposed budget for public hearing"],
                "action_items": ["Public hearings March 4, 6, and 11", "Finance to post budget documents online by February 20"],
                "primary_category": "budget-finance",
                "urgency": "significant",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$1,840,000,000", "$22,000,000"], "vote_tallies": ["8-1"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – March 2025",
        "board_slug": "lcps-school-board",
        "meeting_date": "2025-03-11",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "Following public hearings, the Board directed amendments to the FY2026 budget including additional counselor positions, approved Phase 1 of the 15th high school feasibility study, and adopted a new student data privacy policy restricting third-party vendor data access.",
        "top_decisions": [
            "Directed FY2026 budget amendment adding 15 counselor positions ($1.8M)",
            "Approved 15th high school feasibility study Phase 1 (eastern county siting)",
            "Adopted Student Data Privacy Policy restricting third-party data access",
        ],
        "fiscal_total": "$1,800,000",
        "total_items": 12,
        "fiscal_items": 3,
        "items": [
            {
                "title": "Student Data Privacy Policy Adoption",
                "summary": "The Board adopted a comprehensive Student Data Privacy Policy governing collection, use, and sharing of student data with third-party vendors. The policy requires signed Data Processing Agreements with all vendors, prohibits use of student data for advertising, and mandates annual vendor audits.",
                "decisions": ["Adopted Student Data Privacy Policy effective July 1, 2025"],
                "action_items": ["Technology to audit all 280 third-party vendor agreements by June 30", "Vendors failing to sign DPAs to be discontinued"],
                "primary_category": "technology",
                "urgency": "notable",
                "fiscal_impact": False,
                "key_figures": {"amounts": [], "vote_tallies": ["9-0"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – April 2025",
        "board_slug": "lcps-school-board",
        "meeting_date": "2025-04-08",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board adopted the FY2026 operating budget of $1.855 billion with a 4% salary increase for all staff. The Board also approved school boundary adjustments for 12 elementary schools in the eastern region to relieve overcrowding, effective Fall 2025.",
        "top_decisions": [
            "Adopted FY2026 operating budget of $1.855 billion with 4% staff salary increase",
            "Approved elementary school boundary adjustments effective Fall 2025 (12 schools)",
            "Approved Moorefield Station ES construction contract ($89.2M)",
        ],
        "fiscal_total": "$1,855,000,000",
        "total_items": 14,
        "fiscal_items": 6,
        "items": [
            {
                "title": "FY2026 Operating Budget Adoption",
                "summary": "The Board adopted the FY2026 operating budget of $1.855 billion, a 3.5% increase over FY2025. The budget includes a 4% salary increase for all employees, 105 new positions for enrollment growth, expanded mental health services (25 new counselors), and full funding for the science of reading curriculum rollout.",
                "decisions": ["Adopted FY2026 budget of $1,855,000,000", "Approved 4% salary increase effective July 1, 2025"],
                "action_items": ["Finance to distribute departmental allocations by June 1"],
                "primary_category": "budget-finance",
                "urgency": "significant",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$1,855,000,000"], "vote_tallies": ["7-2"], "schools": []},
            },
            {
                "title": "Elementary School Boundary Adjustments – Eastern Region",
                "summary": "The Board approved boundary adjustments for 12 elementary schools in the eastern Loudoun region to address overcrowding. Approximately 1,240 students will be reassigned. The affected schools include Waxpool, Mill Run, Algonkian, and 9 others. Transportation will be provided for all reassigned students.",
                "decisions": ["Approved boundary adjustments for 12 eastern elementary schools effective Fall 2025", "Directed transportation plan for 1,240 reassigned students"],
                "action_items": ["Reassignment letters to be mailed by May 1", "Transportation routing to be completed by July 15"],
                "primary_category": "schools-education",
                "urgency": "significant",
                "fiscal_impact": False,
                "key_figures": {"amounts": [], "vote_tallies": ["6-3"], "schools": ["Waxpool ES", "Mill Run ES", "Algonkian ES"]},
            },
            {
                "title": "Moorefield Station Elementary School Construction Contract",
                "summary": "The Board awarded the construction contract for the new Moorefield Station Elementary School to Whiting-Turner Contracting Company for $89.2M. The 105,000 sq ft school will serve 900 students with 4 grade-level learning communities, a Maker Space, and shared community spaces. Completion targeted for June 2027.",
                "decisions": ["Awarded $89.2M construction contract to Whiting-Turner Contracting"],
                "action_items": ["Groundbreaking ceremony scheduled for May 2025", "Monthly construction progress reports to Board"],
                "primary_category": "school-construction",
                "urgency": "notable",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$89,200,000"], "vote_tallies": ["9-0"], "schools": ["Moorefield Station Elementary"]},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – May 2025",
        "board_slug": "lcps-school-board",
        "meeting_date": "2025-05-13",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board recognized 6,102 LCPS graduates with a record 96.8% graduation rate, approved a new Athletics Equity Review requiring gender equity audits across all sports programs, and authorized Phase 2 of the 15th high school feasibility study.",
        "top_decisions": [
            "Recognized 6,102 graduates with record 96.8% graduation rate",
            "Approved Athletics Gender Equity Review Policy",
            "Authorized 15th high school Phase 2 feasibility (site selection and cost estimate)",
        ],
        "fiscal_total": None,
        "total_items": 10,
        "fiscal_items": 1,
        "items": [
            {
                "title": "2025 Graduation Rate Report",
                "summary": "LCPS achieved a record 96.8% graduation rate for the Class of 2025, with 6,102 students graduating. The on-time graduation rate for Black students increased from 91.2% to 93.4%. Hispanic graduation rates rose from 93.1% to 95.2%. The dropout rate fell to 1.1%, the lowest in LCPS history.",
                "decisions": ["Accepted 2025 graduation rate report"],
                "action_items": ["Superintendent to present equity-focused intervention plan for remaining gap closure"],
                "primary_category": "schools-education",
                "urgency": "routine",
                "fiscal_impact": False,
                "key_figures": {"amounts": [], "vote_tallies": ["9-0"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – June 2025",
        "board_slug": "lcps-school-board",
        "meeting_date": "2025-06-10",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board held a farewell recognition for outgoing Superintendent Dr. Aaron Spence and welcomed incoming Superintendent Dr. Sandra Williams-Latch. The Board also approved a $3.1M summer learning program for 4,800 students, adopted revised school meal nutrition standards, and approved three new school security contracts.",
        "top_decisions": [
            "Recognized outgoing Superintendent Dr. Aaron Spence for 8 years of service",
            "Approved $3.1M expanded summer learning program for 4,800 students",
            "Adopted revised school meal nutrition standards exceeding USDA requirements",
        ],
        "fiscal_total": "$3,100,000",
        "total_items": 11,
        "fiscal_items": 4,
        "items": [
            {
                "title": "Summer Learning Program 2025 Expansion",
                "summary": "The Board approved an expanded summer learning program serving 4,800 students at a cost of $3.1M, up from 3,200 students the prior year. The program includes intensive reading and math intervention for students at risk, STEM enrichment, and English language development. Six schools will serve as host sites.",
                "decisions": ["Approved expanded summer learning program ($3.1M)", "Directed enrollment priority for students with IEPs and EL designation"],
                "action_items": ["Registration to open June 15", "Principals to directly contact eligible families"],
                "primary_category": "schools-education",
                "urgency": "notable",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$3,100,000"], "vote_tallies": ["9-0"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – August 2025",
        "board_slug": "lcps-school-board",
        "meeting_date": "2025-08-12",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board received Superintendent Dr. Williams-Latch's first report on priorities and 90-day listening tour findings. The Board approved the 2025-26 school year opening, authorized cell phone restrictions to expand to high schools beginning in January 2026, and approved a new tutoring partnership with Virginia public universities.",
        "top_decisions": [
            "Accepted new Superintendent's 90-day listening tour findings and priority framework",
            "Approved cell phone restriction expansion to high schools starting January 2026",
            "Approved university tutoring partnership with GMU, VT, and JMU",
        ],
        "fiscal_total": None,
        "total_items": 12,
        "fiscal_items": 2,
        "items": [
            {
                "title": "Superintendent Williams-Latch 90-Day Report and Priorities",
                "summary": "Dr. Williams-Latch presented findings from her 90-day listening tour including 42 school visits, 18 community forums, and conversations with 2,800 students, staff, and families. Her five priority areas: (1) instructional excellence, (2) whole-child wellness, (3) operational efficiency, (4) community trust, and (5) equity in access.",
                "decisions": ["Accepted Superintendent's 90-day report and five-priority framework"],
                "action_items": ["Staff to develop Year 1 implementation plan by October 2025"],
                "primary_category": "policy-governance",
                "urgency": "notable",
                "fiscal_impact": False,
                "key_figures": {"amounts": [], "vote_tallies": ["9-0"], "schools": []},
            },
            {
                "title": "High School Cell Phone Restriction Policy",
                "summary": "The Board approved expanding the cell phone restriction policy to all 14 LCPS high schools effective January 20, 2026. Students must store personal devices during class periods. Exceptions permitted for learning accommodations, medical needs, and teacher-authorized educational use.",
                "decisions": ["Approved high school cell phone restriction policy effective January 20, 2026"],
                "action_items": ["Principals to engage students and families in fall 2025", "Implementation guidance to be issued by December 1"],
                "primary_category": "policy-governance",
                "urgency": "notable",
                "fiscal_impact": False,
                "key_figures": {"amounts": [], "vote_tallies": ["7-2"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – September 2025",
        "board_slug": "lcps-school-board",
        "meeting_date": "2025-09-09",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board received the 2025-26 opening enrollment of 88,341 students and approved a $5.2M federal Title I grant for 12 high-poverty schools. The Board also approved a revised Special Education Strategic Plan with measurable outcome goals and authorized a competitive bid for division-wide Wi-Fi infrastructure upgrades.",
        "top_decisions": [
            "Accepted opening enrollment: 88,341 students, record for sixth consecutive year",
            "Accepted $5.2M Title I federal grant for 12 high-need schools",
            "Approved revised Special Education Strategic Plan with 3-year outcome goals",
        ],
        "fiscal_total": "$5,200,000",
        "total_items": 11,
        "fiscal_items": 4,
        "items": [
            {
                "title": "Special Education Strategic Plan 2025-2028",
                "summary": "The Board approved a revised Special Education Strategic Plan establishing measurable goals: increase percentage of students with IEPs accessing general education to 72% by 2028, reduce special education disproportionality by 30%, and increase parent satisfaction from 61% to 80%. The plan addresses a state compliance finding from 2023.",
                "decisions": ["Adopted Special Education Strategic Plan 2025-2028"],
                "action_items": ["Special Ed department to present quarterly progress reports", "Parent Advisory Committee to be established by November 2025"],
                "primary_category": "schools-education",
                "urgency": "significant",
                "fiscal_impact": False,
                "key_figures": {"amounts": [], "vote_tallies": ["9-0"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – October 2025",
        "board_slug": "lcps-school-board",
        "meeting_date": "2025-10-14",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board approved the 15th high school site selection for a 70-acre parcel in the Ashburn/One Loudoun area, received the first quarter academic report, and approved a comprehensive athletics equity investment plan adding 18 girls' sports opportunities across the division.",
        "top_decisions": [
            "Approved 15th high school site: 70-acre parcel in Ashburn/One Loudoun area ($38M purchase)",
            "Approved Athletics Equity Investment Plan: 18 new girls' sport opportunities",
            "Accepted Q1 academic report: reading proficiency up 4 points division-wide",
        ],
        "fiscal_total": "$38,000,000",
        "total_items": 12,
        "fiscal_items": 4,
        "items": [
            {
                "title": "15th High School Site Selection and Purchase",
                "summary": "The Board approved the purchase of a 70-acre parcel at Moorefield Station Drive and Ashburn Village Boulevard for $38 million as the site for LCPS's 15th high school. The school will serve 2,400 students and is projected to open in Fall 2029 at a total construction cost of $215 million. Architectural services RFP to be issued in Q1 2026.",
                "decisions": ["Approved $38M site purchase for 15th high school", "Directed RFP for architectural services by February 2026"],
                "action_items": ["Legal to complete purchase by December 2025", "Naming committee to be established in 2026"],
                "primary_category": "school-construction",
                "urgency": "significant",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$38,000,000", "$215,000,000"], "vote_tallies": ["8-1"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – November 2025",
        "board_slug": "lcps-school-board",
        "meeting_date": "2025-11-12",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board approved the FY2027 budget development calendar with an early February superintendent's proposed budget, received Moorefield Station ES construction update (42% complete), and approved a new dual enrollment expansion adding 6 additional community college courses.",
        "top_decisions": [
            "Approved FY2027 budget development calendar (proposed budget: February 10, 2026)",
            "Approved dual enrollment expansion: 6 new NOVA courses available Fall 2026",
            "Received Moorefield Station ES construction update: 42% complete, on schedule",
        ],
        "fiscal_total": None,
        "total_items": 10,
        "fiscal_items": 2,
        "items": [
            {
                "title": "Dual Enrollment Expansion with NOVA Community College",
                "summary": "The Board approved an expansion of the dual enrollment partnership with Northern Virginia Community College, adding 6 new courses available to LCPS high school juniors and seniors beginning Fall 2026. New courses include Cybersecurity Fundamentals, Healthcare Sciences, Entrepreneurship, and three liberal arts courses. Approximately 800 additional students will have access.",
                "decisions": ["Approved 6 new NOVA dual enrollment courses for Fall 2026"],
                "action_items": ["Counseling departments to update course catalogs by December", "MOU amendment to be signed with NOVA by January 2026"],
                "primary_category": "schools-education",
                "urgency": "routine",
                "fiscal_impact": False,
                "key_figures": {"amounts": [], "vote_tallies": ["9-0"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – December 2025",
        "board_slug": "lcps-school-board",
        "meeting_date": "2025-12-09",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board approved a $4.5M STEM initiative for middle schools, received the comprehensive high school capacity relief report recommending the 15th high school as the primary solution, and approved extended calendar options for the 2026-27 school year with a one-week extension to the school year.",
        "top_decisions": [
            "Approved $4.5M Middle School STEM Initiative (11 schools, 3 years)",
            "Endorsed 15th high school as primary capacity solution (projected 2029 opening)",
            "Approved extended school year calendar for 2026-27 (184 instructional days)",
        ],
        "fiscal_total": "$4,500,000",
        "total_items": 11,
        "fiscal_items": 3,
        "items": [
            {
                "title": "Middle School STEM Initiative Approval",
                "summary": "The Board approved a $4.5M three-year initiative to expand STEM education across 11 LCPS middle schools. The program includes dedicated STEM labs, 3D printing equipment, coding curriculum, and teacher certification support. Year 1 targets 4 pilot schools; full implementation by Fall 2027.",
                "decisions": ["Approved $4.5M Middle School STEM Initiative over 3 years", "Directed 4 pilot schools to be identified by January 2026"],
                "action_items": ["Curriculum to develop STEM lab design standards by February 2026"],
                "primary_category": "technology",
                "urgency": "notable",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$4,500,000"], "vote_tallies": ["9-0"], "schools": []},
            },
        ],
    },
    # ── 2026 ──────────────────────────────────────────────────────────────
    {
        "title": "LCPS School Board Business Meeting – January 2026",
        "board_slug": "lcps-school-board",
        "meeting_date": "2026-01-13",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board received the fall 2025 SOL results showing continued improvement, approved the high school cell phone restriction implementation plan, and authorized the 15th high school architectural design RFP. The Board also received a report on the middle school STEM pilot school selection.",
        "top_decisions": [
            "Accepted fall 2025 SOL results: LCPS reading proficiency at 85%, math at 78%",
            "Approved high school cell phone restriction implementation guidance for January 20 launch",
            "Authorized 15th high school architectural services RFP",
        ],
        "fiscal_total": None,
        "total_items": 10,
        "fiscal_items": 2,
        "items": [
            {
                "title": "Fall 2025 SOL Assessment Results",
                "summary": "LCPS students achieved the highest test scores in division history on fall 2025 Standards of Learning assessments. Reading proficiency reached 85% (state average: 78%), math 78% (state: 70%). The science of reading curriculum showed measurable impact: 3rd grade reading improved 7 points. Achievement gaps between demographic groups narrowed for the second consecutive year.",
                "decisions": ["Accepted fall 2025 SOL results"],
                "action_items": ["Curriculum to publish school-level data dashboard", "Reading specialists to continue Tier 2 interventions"],
                "primary_category": "schools-education",
                "urgency": "routine",
                "fiscal_impact": False,
                "key_figures": {"amounts": [], "vote_tallies": ["9-0"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – February 2026",
        "board_slug": "lcps-school-board",
        "meeting_date": "2026-02-10",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "Superintendent Dr. Williams-Latch presented the FY2027 proposed budget of $1.92 billion, a 3.5% increase focusing on teacher compensation, mental health expansion, and accelerated construction funding. The Board also approved a new Career and Technical Education expansion plan.",
        "top_decisions": [
            "Approved FY2027 proposed budget of $1.92 billion for public hearing",
            "Approved Career and Technical Education expansion: 12 new program pathways",
            "Accepted 15th high school architectural services award ($4.2M)",
        ],
        "fiscal_total": "$1,920,000,000",
        "total_items": 13,
        "fiscal_items": 5,
        "items": [
            {
                "title": "FY2027 Superintendent's Proposed Budget",
                "summary": "Superintendent Williams-Latch presented the FY2027 proposed budget of $1.92 billion, emphasizing teacher recruitment and retention (4.5% salary increase), expansion of mental health services to 95 additional counselors, and $280M in capital projects including the 15th high school land preparation. The budget also funds 3 new elementary schools in planning stages.",
                "decisions": ["Approved FY2027 proposed budget for public hearing", "Public hearings scheduled March 3, 5, and 10"],
                "action_items": ["Budget documents to be posted online February 14"],
                "primary_category": "budget-finance",
                "urgency": "significant",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$1,920,000,000"], "vote_tallies": ["8-1"], "schools": []},
            },
            {
                "title": "Career and Technical Education Program Expansion",
                "summary": "The Board approved expansion of CTE pathways to add 12 new programs across LCPS high schools, including Cybersecurity, AI & Machine Learning, Healthcare Technology, Skilled Trades, and Advanced Manufacturing. The $6.8M investment over two years will create 1,400 additional CTE seats for students.",
                "decisions": ["Approved CTE expansion plan with 12 new pathways ($6.8M over 2 years)"],
                "action_items": ["CTE director to coordinate with industry partners for work-based learning", "Implementation begins Fall 2026 in 4 pilot high schools"],
                "primary_category": "schools-education",
                "urgency": "notable",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$6,800,000"], "vote_tallies": ["9-0"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – March 2026",
        "board_slug": "lcps-school-board",
        "meeting_date": "2026-03-10",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "Following public hearings on the FY2027 budget, the Board directed amendments to add 8 school psychologist positions and fund a free breakfast program expansion to all Title I schools. The Board also approved Phase 1 site development for the 15th high school.",
        "top_decisions": [
            "Directed FY2027 amendment: 8 additional school psychologist positions ($1.4M)",
            "Directed expansion of free breakfast program to all 24 Title I schools",
            "Approved 15th high school Phase 1 site development ($8.5M)",
        ],
        "fiscal_total": "$9,900,000",
        "total_items": 11,
        "fiscal_items": 4,
        "items": [
            {
                "title": "FY2027 Budget Amendments Following Public Hearings",
                "summary": "Following three public hearings with over 500 community participants, the Board directed two amendments to the FY2027 budget: (1) addition of 8 school psychologist positions to address the national shortage and improve student mental health support ratios, and (2) expansion of the universal free breakfast program to all 24 Title I schools.",
                "decisions": ["Directed $1.4M amendment for 8 psychologist positions", "Directed $1.2M for free breakfast expansion to Title I schools"],
                "action_items": ["Finance to prepare amended budget for April adoption"],
                "primary_category": "budget-finance",
                "urgency": "notable",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$1,400,000", "$1,200,000"], "vote_tallies": ["8-1"], "schools": []},
            },
        ],
    },
    {
        "title": "LCPS School Board Business Meeting – April 2026",
        "board_slug": "lcps-school-board",
        "meeting_date": "2026-04-14",
        "source_url": "https://lcps.org/boardofed",
        "meeting_overview": "The Board adopted the FY2027 operating budget of $1.935 billion with a 4.5% salary increase and approved the FY2027 Capital Improvement Program of $385 million. The Board also adopted a revised Grading and Reporting Policy and approved partnership with a non-profit for after-school programming at 8 high-poverty schools.",
        "top_decisions": [
            "Adopted FY2027 operating budget: $1.935 billion with 4.5% salary increase",
            "Adopted FY2027 Capital Improvement Program: $385 million",
            "Adopted revised Grading and Reporting Policy (standards-based grading for K-8)",
        ],
        "fiscal_total": "$1,935,000,000",
        "total_items": 14,
        "fiscal_items": 6,
        "items": [
            {
                "title": "FY2027 Operating Budget Adoption",
                "summary": "The Board adopted the FY2027 operating budget of $1.935 billion, a 4.3% increase over FY2026. All LCPS employees receive a 4.5% salary increase effective July 1. The budget funds 112 new positions, expanded mental health services, universal free breakfast at all Title I schools, and 8 new school psychologists.",
                "decisions": ["Adopted FY2027 budget of $1,935,000,000", "Approved 4.5% salary increase for all employees effective July 1, 2026"],
                "action_items": ["Finance to distribute departmental budgets by June 1"],
                "primary_category": "budget-finance",
                "urgency": "significant",
                "fiscal_impact": True,
                "key_figures": {"amounts": ["$1,935,000,000"], "vote_tallies": ["7-2"], "schools": []},
            },
            {
                "title": "Revised Grading and Reporting Policy – Standards-Based Grading",
                "summary": "The Board adopted a revised Grading and Reporting Policy transitioning K-8 schools to standards-based grading by Fall 2027, with pilot implementation in grades K-2 beginning Fall 2026. The policy eliminates traditional letter grades for elementary students, replacing them with proficiency descriptors and narrative progress reports.",
                "decisions": ["Adopted standards-based grading policy for K-8 implementation by Fall 2027", "Approved K-2 pilot beginning Fall 2026"],
                "action_items": ["Curriculum to develop family communication and training plan by July 2026"],
                "primary_category": "policy-governance",
                "urgency": "notable",
                "fiscal_impact": False,
                "key_figures": {"amounts": [], "vote_tallies": ["6-3"], "schools": []},
            },
        ],
    },
]


async def seed():
    async with async_session() as session:
        # Remove existing LCPS meetings if re-running
        await session.execute(
            text("DELETE FROM agenda_items WHERE meeting_id IN (SELECT id FROM meetings WHERE board_slug = 'lcps-school-board' AND id != 3)")
        )
        await session.execute(
            text("DELETE FROM meetings WHERE board_slug = 'lcps-school-board' AND id != 3")
        )
        await session.commit()

        for m_data in MEETINGS:
            items = m_data.pop("items", [])
            # Convert date string to datetime.date object
            if isinstance(m_data.get("meeting_date"), str):
                m_data["meeting_date"] = date.fromisoformat(m_data["meeting_date"])
            meeting = models.Meeting(**m_data)
            session.add(meeting)
            await session.flush()  # get meeting.id

            for item_data in items:
                kf = item_data.pop("key_figures", {})
                item = models.AgendaItem(
                    meeting_id=meeting.id,
                    key_figures=kf,
                    **item_data,
                )
                session.add(item)

            # Update total_items
            meeting.total_items = len(items)
            meeting.fiscal_items = sum(1 for i in items if i.get("fiscal_impact"))

        await session.commit()
        print(f"Seeded {len(MEETINGS)} LCPS meetings with agenda items")


if __name__ == "__main__":
    asyncio.run(seed())
